"""add detect telemetry fields

Revision ID: 3543d1f2940c
Revises: 8e639366e8bc
Create Date: 2026-09-04 16:11:20.284171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3543d1f2940c'
down_revision: Union[str, Sequence[str], None] = '8e639366e8bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # NOTE: op.create_table('frame_scores', ...) below was added by hand —
    # autogenerate didn't detect it because the local dev DB already had this
    # table (FastAPI's --reload picked up the new FrameScore model and its
    # lifespan hook's create_all_tables() dev shortcut created it live). A
    # fresh DB at the previous revision still needs it created here.
    op.create_table(
        'frame_scores',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('prediction_id', sa.String(length=36), nullable=False),
        sa.Column('track_id', sa.Integer(), nullable=False),
        sa.Column('frame_index', sa.Integer(), nullable=False),
        sa.Column('timestamp', sa.Float(), nullable=False),
        sa.Column('fake_probability', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_frame_scores_prediction_id'), 'frame_scores', ['prediction_id'], unique=False)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('n_frames_total', sa.Integer(), nullable=True))
    op.add_column('predictions', sa.Column('n_frames_analyzed', sa.Integer(), nullable=True))
    op.add_column('predictions', sa.Column('video_width', sa.Integer(), nullable=True))
    op.add_column('predictions', sa.Column('video_height', sa.Integer(), nullable=True))
    op.add_column('predictions', sa.Column('duration_seconds', sa.Float(), nullable=True))
    op.add_column('predictions', sa.Column('processing_time_ms', sa.Float(), nullable=True))
    op.add_column('predictions', sa.Column('n_faces_detected', sa.Integer(), nullable=True))
    op.add_column('predictions', sa.Column('model_run_id', sa.String(length=64), nullable=True))
    op.add_column('predictions', sa.Column('original_path', sa.String(length=1024), nullable=True))
    op.add_column('predictions', sa.Column('heatmap_only_path', sa.String(length=1024), nullable=True))
    op.add_column('suspicious_frames', sa.Column('original_path', sa.String(length=1024), nullable=True))
    op.add_column('suspicious_frames', sa.Column('heatmap_only_path', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suspicious_frames', 'heatmap_only_path')
    op.drop_column('suspicious_frames', 'original_path')
    op.drop_column('predictions', 'heatmap_only_path')
    op.drop_column('predictions', 'original_path')
    op.drop_column('predictions', 'model_run_id')
    op.drop_column('predictions', 'n_faces_detected')
    op.drop_column('predictions', 'processing_time_ms')
    op.drop_column('predictions', 'duration_seconds')
    op.drop_column('predictions', 'video_height')
    op.drop_column('predictions', 'video_width')
    op.drop_column('predictions', 'n_frames_analyzed')
    op.drop_column('predictions', 'n_frames_total')
    # ### end Alembic commands ###
    op.drop_index(op.f('ix_frame_scores_prediction_id'), table_name='frame_scores')
    op.drop_table('frame_scores')
